runtime: python39
entrypoint: gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind :$PORT main:app
instance_class: F1

handlers:
  - url: /.*
    script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "./service_account.json"
